const DEFAULT_TEXT_COLOR = '#666666';
const DEFAULT_TEXT_COLOR_REVERSE = '#ffffff';
const PRIMARY_COLOR = '#F9BA48';
const DEFAULT_COLOR = '#f6f6f6';

export {
  DEFAULT_TEXT_COLOR,
  DEFAULT_TEXT_COLOR_REVERSE,
  DEFAULT_COLOR,
  PRIMARY_COLOR,
};
