export const GENDER_OPTIONS = [
  {key: 'm', text: 'Male', value: 'male'},
  {key: 'f', text: 'Female', value: 'female'},
  {key: 'o', text: 'Other', value: 'other'},
];

export const RANKS = [
  '18K',
  '17K',
  '16K',
  '15K',
  '14K',
  '13K',
  '12K',
  '11K',
  '10K',
  '9K',
  '8K',
  '7K',
  '6K',
  '5K',
  '4K',
  '3K',
  '2K',
  '1K',
  '1D',
  '2D',
  '3D',
  '4D',
  '5D',
  '6D',
  '7D',
  '8D',
  '9D',
  '1P',
  '2P',
  '3P',
  '4P',
  '5P',
  '6P',
  '7P',
  '8P',
  '9P',
];

export const RANK_OPTIONS = [
  {key: '18K', text: '18K', value: '18K'},
  {key: '17K', text: '17K', value: '17K'},
  {key: '16K', text: '16K', value: '16K'},
  {key: '15K', text: '15K', value: '15K'},
  {key: '14K', text: '14K', value: '14K'},
  {key: '13K', text: '13K', value: '13K'},
  {key: '12K', text: '12K', value: '12K'},
  {key: '11K', text: '11K', value: '11K'},
  {key: '10K', text: '10K', value: '10K'},
  {key: '9K', text: '9K', value: '9K'},
  {key: '8K', text: '8K', value: '8K'},
  {key: '7K', text: '7K', value: '7K'},
  {key: '6K', text: '6K', value: '6K'},
  {key: '5K', text: '5K', value: '5K'},
  {key: '4K', text: '4K', value: '4K'},
  {key: '3K', text: '3K', value: '3K'},
  {key: '2K', text: '2K', value: '2K'},
  {key: '1K', text: '1K', value: '1K'},
  {key: '1D', text: '1D', value: '1D'},
  {key: '2D', text: '2D', value: '2D'},
  {key: '3D', text: '3D', value: '3D'},
  {key: '4D', text: '4D', value: '4D'},
  {key: '5D', text: '5D', value: '5D'},
  {key: '6D', text: '6D', value: '6D'},
  {key: '7D', text: '7D', value: '7D'},
  {key: '8D', text: '8D', value: '8D'},
  {key: '9D', text: '9D', value: '9D'},
  {key: '1P', text: '1P', value: '1P'},
  {key: '2P', text: '2P', value: '2P'},
  {key: '3P', text: '3P', value: '3P'},
  {key: '4P', text: '4P', value: '4P'},
  {key: '5P', text: '5P', value: '5P'},
  {key: '6P', text: '6P', value: '6P'},
  {key: '7P', text: '7P', value: '7P'},
  {key: '8P', text: '8P', value: '8P'},
  {key: '9P', text: '9P', value: '9P'},
];
